name: C/C++ build/test for rkmh2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: make
      run: make
    - name: make test
      run: make test
